[package]
name = "wgpu-problem"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.3"
# first bad (https://github.com/gfx-rs/wgpu/pull/5884):
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "0a76c0fa84e5e8c10c62f0a19fb54b65c0a4f6e2" }
# last good (https://github.com/gfx-rs/wgpu/pull/5858):
#wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "c9a2d972ad40ca325ccc1aba71767040a51c7c11" }
